### ISSUE TITLE
Virtual node does not have correct gpu (nvidia.com/gpu) resource capacity

### ISSUE THREAD

**Issue by jalola** [liqotech/liqo#1035]
#### What happened:

Virtual node seems to have correct capacity (allocatable) of CPU and RAM resources but not GPU.

#### What you expected to happen:

Virtual node updates the GPU status correctly

#### How to reproduce it (as minimally and precisely as possible):

1. Set up Liqo
2. Add a GPU instance in remote cluster
3. Check the virtual node

#### Anything else we need to know?:

Example:
Capacity of a gpu node on remote cluster
![image](https://user-images.githubusercontent.com/1896808/148004815-5735b33f-c2a2-4ff8-bf7e-70dabcd6449d.png)

Virtual node capacity:
![image](https://user-images.githubusercontent.com/1896808/148004788-cdf25f50-58f5-4d90-a041-3f3c5de6c413.png)

#### Environment:
- Liqo version: v0.3.2-beta.2
- Kubernetes version (use `kubectl version`): v1.21.0
- Cloud provider or hardware configuration: 2 EKS clusters
- Network plugin and version:
- Install tools: liqoctl
- Others:

**Comment by aleoli** [comment]
Hi @jalola, that issue should be due to how Liqo handles resources: it collects all the not-allocated resources and scale them by a factor before sharing them to a remote cluster.

This factor is 90% by default, and it can be overwritten setting the `resource-sharing-percentage` flag in `liqoctl install` (the command is idempotent you have not to reinstall Liqo, but it is safer to tear down the peering before that) or setting this value in your `values.yaml` file if using helm.

I think that we have to change this behavior (at least for small numbers) to allow the sharing of small quantities of resources.

Can you please try to set the sharing percentage to 100% or to increase the number of GPUs to check that it is a math rounding problem and not some other logical problem?

**Comment by jalola** [comment]
I increased to 2 gpu, but the virtual node GPU is still 0.
I will check the `resource-sharing-percentage`

**Comment by jalola** [comment]
Updated: 
set `resource-sharing-percentage` to 100 should solve the issue.

When `resource-sharing-percentage` == 90:
- Foreign cluser: 4 instances, each has 1 GPU --> Local cluster will see 0 GPU (4 * int(1 * 0.9) = 0)
- Foreign cluser: 1 instance, 4 GPU --> Local cluster will see 3 GPU (1 * int(4 * 0.9) = 3)

I closed issue.
