### ISSUE TITLE
[Question] How does Liqo scale?

### ISSUE THREAD

**Issue by soggycactus** [liqotech/liqo#1101]
According to [Considerations for large clusters](https://kubernetes.io/docs/setup/best-practices/cluster-large/), a single Kubernetes cluster is made to scale to:

- No more than 110 pods per node
- No more than 5000 nodes
- No more than 150000 total pods
- No more than 300000 total containers

In addition, [iptables operations slow down dramatically in large clusters, typically ~ 10K Services](https://kubernetes.io/docs/concepts/services-networking/service/#ipvs). While you can remove the iptables bottleneck by using a different CNI such as Cilium, this is still relatively new and most existing clusters today use iptables. 

Given all of this - _How does Liqo help you scale beyond the limits of a single cluster?_

From reading & experimenting with Liqo, it appears that "Shadow" Pods & Services are created on the home cluster when workloads are offloaded to the remote cluster; does this mean the home cluster is still beholden to the same limits described above?

**Comment by giorio94** [comment]
Hi @soggycactus,

Before delving into your question, I have to clarify that we did not yet manage to test liqo at the scale you are mentioning, due to limitations of our testbed. Hence, the following answers come from experience at a lower scale (more details in the following) and theoretical considerations.

As for the different Kubernetes limits:

* **Pods per node**: a single Liqo virtual node is not limited to 110 pods, as the actual containers are offloaded to a remote clusterwith multiple physical nodes. We successfully hosted more than 10K pods on a single virtual node, achieving startup times comparable to those of vanilla Kubernetes and with the virtual kubelet requiring at most 0.5CPU (during the transient) and 500MB of RAM.
* **Total nodes**: Liqo abstracts a remote cluster, possibly made up of multiple nodes, as a single node in the home cluster, hence reducing the number of nodes perceived by the home cluster. This allows to go beyond the vanilla Kubernetes limits considering the nodes as a whole. Still, in this respect and as of today, we have only tested Liqo with a number of virtual nodes in the order of hundreds.
* **Total pods**: as you correctly pointed out, with the current Liqo approach a shadow copy of each offloaded pod is present in the local cluster (indeed, higher level abstractions such as deployment create the pods in the home cluster, then the scheduler selects a virtual node as a target and finally Liqo takes charge of offloading them to the remote cluster). Although they are not executed by the home cluster and they do not consume local resources, the shadow pods are present as objects in the home etcd database, thus possibly counting towards the maximum limit (I don't actually know the details about the origin of the maximum number of pods in Kubernetes).
* **Total services**": also in this case, Liqo ensures services are present both in the local and in the remote cluster (for a subset of namespaces, depending on the configuration), to allow for transparent inter-cluster communication. In addition, it also synchronizes the endpointslices resources associated with each service. Leveraging endpointslices instead of plain old endpoints allows Liqo to better deal with high numbers of distributed backend pods thanks to sharding. Still, you might hit the typical Kubernetes limitations (we have not yet performed tests in this direction).
* **Total containers**: I would say this does not introduce particular concerns in addition to ones related to the number of pods, as containers are not physically executed in the home cluster.

**Comment by soggycactus** [comment]
> Hi @soggycactus,
> 
> Before delving into your question, I have to clarify that we did not yet manage to test liqo at the scale you are mentioning, due to limitations of our testbed. Hence, the following answers come from experience at a lower scale (more details in the following) and theoretical considerations.
> 
> As for the different Kubernetes limits:
> 
>     * **Pods per node**: a single Liqo virtual node is not limited to 110 pods, as the actual containers are offloaded to a remote cluster with multiple physic nodes. We successfully hosted more than 10K pods on a single virtual node, achieving startup times comparable to those of vanilla Kubernetes and with the virtual kubelet requiring at most 0.5CPU (during the transient, practically 0 at rest) and 500MB of RAM.
> 
>     * **Total nodes**: Liqo abstracts a remote cluster, possibly made up of multiple nodes, as a single node in the home cluster, hence reducing the number of nodes perceived by the home cluster. This allows to go beyond the vanilla Kubernetes limits considering the nodes as a whole. Still, in this respect and as of today, we have only tested Liqo with a number of virtual nodes in the order of hundreds.
> 
>     * **Total pods**: as you correctly pointed out, with the current Liqo approach a shadow copy of each offloaded pod is present in the local cluster (indeed, higher level abstractions such as deployments create the pods in the home cluster, then the scheduler selects a virtual node as a target and finally Liqo takes charge of offloading them to the remote cluster). Although they are not executed by the home cluster and they do not consume local resources, the shadow pods are present as objects in the home etcd database, thus possibly counting towards the maximum limit (I don't actually know the details about the origin of the maximum number of pods in Kubernetes).
> 
>     * **Total services**: also in this case, Liqo ensures services are present both in the local and in the remote cluster (for a subset of namespaces, depending on the configuration), to allow for transparent inter-cluster communication. In addition, it also synchronizes the endpointslices resources associated with each service. Leveraging endpointslices instead of plain old endpoints allows Liqo to better deal with high numbers of distributed backend pods thanks to sharding. Still, you might hit the typical Kubernetes limitations (we have not yet performed tests in this direction).
> 
>     * **Total containers**: I would say this does not introduce particular concerns in addition to ones related to the number of pods, as containers are not physically executed in the home cluster.

Hi @giorio94 thank you for the quick response!

This does answer some of my questions - for context I work at a company that offers a platform-as-a-service and we are looking at potentially using Kubernetes under the hood. Naturally, questions about scalability came up, and I found Liqo while investigating options for a multi-cluster control plane. 

I would be curious what you think of this: it seems Liqo is best suited for environments that don't require a single centralized "control plane" across multiple clusters. As you said, offloaded pods & services will still be represented in the local cluster where they were created. The foreign cluster "reflects" services and creates a ShadowPod that manages the lifecycle of the offloaded pod on the remote cluster. 

By this logic if you use Liqo to scale to multiple clusters, but treated a "home" cluster as the single point of entry for creating workloads, you will still end up approaching the pod/service limit for a single cluster described above. Liqo effectively creates one big cluster, and works best when there is not a single point of entry. Let me know if you believe this is an accurate statement. 

I think what I may be looking for is cluster federation - we want to use multiple K8s clusters to run our users' deployments, but provide a single API in our infrastructure that schedules the workloads. We could use Liqo, but I feel we would end up writing a service that did round-robin allocation of workloads to clusters, which to me kind of defeats the point. 

Again, I would love to hear your thoughts on this - Liqo is a really amazing project, and I have been impressed by how easy it is to use when investigating it.

**Comment by giorio94** [comment]
> 
> Hi @giorio94 thank you for the quick response!
> 
> This does answer some of my questions - for context I work at a company that offers a platform-as-a-service and we are looking at potentially using Kubernetes under the hood. Naturally, questions about scalability came up, and I found Liqo while investigating options for a multi-cluster control plane.
> 
> I would be curious what you think of this: it seems Liqo is best suited for environments that don't require a single centralized "control plane" across multiple clusters. As you said, offloaded pods & services will still be represented in the local cluster where they were created. The foreign cluster "reflects" services and creates a ShadowPod that manages the lifecycle of the offloaded pod on the remote cluster.
> 
> By this logic if you use Liqo to scale to multiple clusters, but treated a "home" cluster as the single point of entry for creating workloads, you will still end up approaching the pod/service limit for a single cluster described above. Liqo effectively creates one big cluster, and works best when there is not a single point of entry. Let me know if you believe this is an accurate statement.

I think this is definitely correct. As a bit of additional context, this behavior stems from the initial design choice of integrating as much as possible with vanilla Kubernetes objects (i.e., pods, services, endpointslices, ...). We believe this has the great advantage of simplifying the usability of the system, given standard practice and tools can be transparently applied also in case of multiple clusters peered with Liqo (e.g., you create standard deployments/statefulsets to describe the applications), as well as it allows to inspect all pods for any problems as usual, even if running remotely.

This obviously implies some trade-offs, and the main one regards the scalability limitations you are mentioning (especially in case of a single entry point cluster), given that all objects are virtually present also in the home cluster where they are created. Which, by the way, is something inherent in all projects which leverage the Virtual Kubelet under the hood. An alternative solution would be to adopt custom high-level APIs (a LiqoDeployment, for the sake of exemplification), to express the desire for creating e.g., deployments on (possibly subset of) the clusters. This would limit the creation of high-cardinality objects (e.g., pods) in the home cluster, at the cost of dealing with non-standard APIs and reducing the overall observability of the system.

> 
> I think what I may be looking for is cluster federation - we want to use multiple K8s clusters to run our users' deployments, but provide a single API in our infrastructure that schedules the workloads. We could use Liqo, but I feel we would end up writing a service that did round-robin allocation of workloads to clusters, which to me kind of defeats the point.

I believe that a possible advantage of Liqo in scenarios like that is that workloads can be automatically scheduled on the best available cluster (e.g., depending on the available resources) and possible additional policies (e.g, affinities to keep applications close together), just as you would do with standard Kubernetes nodes. Another one is that Liqo transparently provides traditional pod-to-pod connectivity across multiple remote clusters. Still, that mainly depends on your actual requirements: in case of no  inter-cluster communication is required (or it is provided by other means), allocation is mainly static and you are not constrained to standard Kubernetes API, then a KubeFed-like federation approach might be better suited, or you might even let your backend to collect the requests, select a cluster and directly start the workload there. I don't know if that might make sense to you.

> 
> Again, I would love to hear your thoughts on this - Liqo is a really amazing project, and I have been impressed by how easy it is to use when investigating it.

Really glad to hear so!

**Comment by giorio94** [comment]
Closing, due to inactivity. @soggycactus feel free to reopen if necessary.
