### ISSUE TITLE
Support Go 1.19

### ISSUE THREAD

**Issue by andig** [liqotech/liqo#1371]
https://github.com/Homebrew/homebrew-core/pull/107165 fails due to 

```
./liqoctl completion bash
panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.19 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.19 set. Notably, if go1.19 adds a moving garbage collector, this program is unsafe to use.

goroutine 1 [running]:
go4.org/unsafe/assume-no-moving-gc.init.0()
	/Users/andig/go/pkg/mod/go4.org/unsafe/assume-no-moving-gc@v0.0.0-20211027215541-db492cf91b37/untested.go:25 +0x19c
```

This can be fixed by upgrading go4.org/unsafe/assume-no-moving-gc according to https://github.com/lucas-clemente/quic-go/issues/3491

**Comment by giorio94** [comment]
Hi @andig,

The problem you mentioned afflicting liqoctl appears to be caused by a slightly out-of-date version of the [go-ipam package](https://github.com/metal-stack/go-ipam), which in turn depends on `go4.org/unsafe/assume-no-moving-gc`. I just opened a PR to bump that component to the latest version, which works correctly with go 1.19. If all tests succeed, we will soon release a new version of liqoctl including the fix.
