### ISSUE TITLE
DaemonSet pods scheduled on virtual-nodes and result in OffloadingBackOff

### ISSUE THREAD

**Issue by GitBurtHET** [liqotech/liqo#1398]
Previous correspondence on the Liqo Slack channel indicated that this issue is already known to the developers. This GitHub issue could help another Liqo user. And, could possibly help solve it more definitively in the future.

#### What happened:
DaemonSets schedule pods to all Kubernetes worker nodes, and thus also Liqo's virtual-nodes. This results in OffloadingBackOff errors for these DaemonSet pods.

#### What you expected to happen:
Since virtual-nodes are abstracted clusters, DaemonSets don't need to schedule pods on them.

#### How to reproduce it (as minimally and precisely as possible):
Install Liqo & liqoctl 0.4, peer two clusters and make sure a virtual-node is created for the remote cluster.

#### Anything else we need to know?:
A few notes:

Only Liqo release 0.4 works stable for me. Is this issue already solved in future releases?

I stumbled on a race condition when offloading namespaces and needed to untaint the virtual-node. I know this is solved in a newer release by using a specific label on the namespace. Only,  I hope this isn't related to this DaemonSet issue.
`kubectl taint nodes liqo-cluster-1 virtual-node.liqo.io/not-allowed=true:NoExecute-`

The following script is a workaround to remove the errors. It iterates and searches for not running pods managed by DaemonSets and patches the DaemonSet YAML definition to exclude virtual-nodes for scheduling.

```
#!/bin/bash

for CLUSTER in cluster-1 cluster-2
do
export KUBECONFIG=/root/.kube/${CLUSTER}

  while read NAME TYPE NAMESPACE
  do
      if [ $TYPE == "DaemonSet" ]
      then
          echo "patching ${TYPE} ${NAME} in ${NAMESPACE}"
          cat <<EOF > ${PWD}/daemonset_patch.yaml
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: liqo.io/type
                    operator: NotIn
                    values:
                      - virtual-node
EOF
          kubectl patch daemonset $NAME -n $NAMESPACE --patch-file ${PWD}/daemonset_patch.yaml
          rm -rf ${PWD}/daemonset_patch.yaml
      fi
  done <<< "$(kubectl get pods -A --field-selector=status.phase!=Running -o custom-columns=':metadata.ownerReferences[0].name,:metadata.ownerReferences[0].kind,:metadata.namespace' --no-headers)"

done
```

#### A definitive solution:
Implementing the mechanic of the script in Golang would not be a good definitive solution I think. Patching Kubernetes YAML definitions of other workloads sounds scary to me (what could go wrong?). Also, GitOps tools manage Kubernetes YAML, but they reconcile changes not present in Git, then you need to exclude specific changes explicitly in the GItOps tool.

#### Environment:
- Liqo version: 0.4:
- Kubernetes version (use `kubectl version`): 1.22
- Cloud provider or hardware configuration: AWS EKS
- Network plugin and version: Cilium 1.12.0
- Install tools: Terraform + liqoctl

**Comment by giorio94** [comment]
Hi @GitBurtHET,

> Previous correspondence on the Liqo Slack channel indicated that this issue is already known to the developers. This GitHub issue could help another Liqo user. And, could possibly help solve it more definitively in the future.

Thanks for the detailed report about this issue. 

As an additional note, this issue is also acknowledged in the [official documentation](https://docs.liqo.io/en/v0.5.4/usage/reflection.html#pods-offloading), suggesting the addition of an appropriate `nodeAffinity` to the DaemonSets to prevent the creation of pods for virtual nodes (as you also pointed out). Yet, this is required only for *system DaemonSets* (e.g., `kube-proxy`, CNIs, ...) that are characterized by wildcard *tolerations*, thus tolerating also the *taint* leveraged by Liqo to prevent the scheduling on virtual nodes. Differently, this patch is not required in case of standard DaemonSets, as the node *taint* is sufficient (given that the pods do not have the corresponding toleration). 

> I stumbled on a race condition when offloading namespaces and needed to untaint the virtual-node. I know this is solved in a newer release by using a specific label on the namespace. Only, I hope this isn't related to this DaemonSet issue.
kubectl taint nodes liqo-cluster-1 virtual-node.liqo.io/not-allowed=true:NoExecute-

Yes, manually removing the node taint affects the DaemonSet issue, since this causes all Daemonsets (not only the ones with wildcard tolerations) to create pods for the virtual nodes. Additionally, it also allows pods living in namespaces not enabled for offloading to being scheduled on virtual nodes, and remaining in a failure status. 

> Implementing the mechanic of the script in Golang would not be a good definitive solution I think. Patching Kubernetes YAML definitions of other workloads sounds scary to me (what could go wrong?). Also, GitOps tools manage Kubernetes YAML, but they reconcile changes not present in Git, then you need to exclude specific changes explicitly in the GItOps tool.

AFAIK, the only automatic solution would be patching the DaemonSets as you mentioned. Yet, this sounds scary to me too, as it would mean modifying external and already existing resources, likely critical for the cluster functioning, as well as possibly starting *fighting* against other controllers or GitOps tools.
