### ISSUE TITLE
Allow to configure a fixed amount of resources offered to each peer, unrelated from the available ones 

### ISSUE THREAD

**Issue by Sharathmk99** [liqotech/liqo#1478]
#### What happened:

Our Remote Cluster is created using Azure VM scale set with auto scaling features for GPU based nodes and default to 0 nodes. 
I was able to install Liqo in both Local and remote cluster and peering between the cluster is successful. But when I describe the virtual node capability has 0 GPU’s. 

How can I configure virtual node with arbitrary resources, as by default remote cluster doesn’t have static nodes.

#### What you expected to happen:
Should be able to configure virtual node with arbitrary resources so local cluster can schedule pods to remote cluster. 

#### How to reproduce it (as minimally and precisely as possible):
Create remote cluster with 0 GPU worker nodes and try to schedule pod in local cluster with GPU. 

#### Environment:
- Liqo version: 0.5
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: onpremise and azure
- Network plugin and version:
- Install tools:
- Others:

**Comment by giorio94** [comment]
By default, liqo characterizes virtual nodes with an amount of resources that is a percentage of the free resources available in the target cluster. Still, it supports the possibility of delegating the computation of the resources offered to a given peer to an external component, which might operate based on any logic of interest (ranging from returning a fixed amount, as it might be suitable in your scenario, to performing complex computations for brokering use-cases). 

Practically speaking, this requires developing a component implementing the server side of the [resource reader gRPC interface](https://github.com/liqotech/liqo/blob/master/pkg/liqo-controller-manager/resource-request-controller/resource-monitors/resource-reader.proto), and configuring the liqo controller manager to delegate requests to it, rather that performing the default computation (i.e., setting the `--external-monitor=endpoint` flag). To this end, there is an ongoing effort to better document this liqo functionality, as well as provide a skeleton of the component based on a simple use-case, ready to be extended for more complex scenarios.

**Comment by giorio94** [comment]
Hey @Sharathmk99,

I just wanted to say that we recently improved the Liqo functionality which enables the possibility of delegating to an external plugin the computation of the amount of resources offered to a given peer; specifically, Liqo v0.6.1 also includes better documentation about this feature.

In addition, we created a new repository (https://github.com/liqotech/liqo-resource-plugins/), serving both as a collection of already existing plugins, and as a guideline to develop new ones. Currently, it includes the *fixed-resources* plugin, which allows you to manually override the amount of resources offered with arbitrary values (e.g., accounting for autoscaling, as in your use-case).

I'm closing this issue for the moment, since I think the above addresses your requirements. Feel free to reopen it if you feel something is still missing, or not working as you would expect.
