### ISSUE TITLE
[Feature] Peer over ingress

### ISSUE THREAD

**Issue by tom-asmblr** [liqotech/liqo#1861]
Hello, thanks for liqo, it looks fantastic.

I have a question about peering, currently, it seems like you need peer over a NodePort/LoadBalancer, is it possible to be able to spin up and ingress in front of the relevant services (liqo-auth, liqo-gateway etc) and connect that way? We already use an underlying gke loadbalancer (used by nginx-ingress), so it's seems weird to expose more endpoints than required. Thanks!

**Comment by cheina97** [comment]
Hi @tom-asmblr, it is possible to use an ingress to expose the liqo-auth service. Instead the liqo-gateway cannot be exposed through a common ingress (proxies like nginx which works with http only) because it uses UDP.

You can enable ingress for liqo-auth with these values:
https://github.com/aleoli/liqo/blob/04059c16d0e00543cbc979a6cbf196d9d857eb25/deployments/liqo/values.yaml#L258-L268

**Comment by frisso** [comment]
@tom-asmblr Please feel free to suggest how to improve the documentation here: https://docs.liqo.io/en/v0.8.3/installation/requirements.html#connectivity
(the ingress option was mentioned but, given your question, it may not 100% clear)

**Comment by tom-asmblr** [comment]
Thanks for thelp @cheina97 and @frisso - I missed this because we're using the liqoctl install command to install liqo, which doesn't seem to support that network flag. Probably best to use `--only-output-values`, modify the values, then apply from that?

**Comment by cheina97** [comment]
@tom-asmblr when you use `liqoctl install` you can use the `--set` flag to override a helm value. Consider that `liqoctl install` uses helm to install liqo.

https://docs.liqo.io/en/v0.8.3/installation/install.html#customization-options
