### ISSUE TITLE
while using Remote offloading strategy the pod is going into the crushloopbackoff state.

### ISSUE THREAD

**Issue by shegurisuresh** [liqotech/liqo#1903]
#### What happened:

I have deployed the cluster using Terraform modules and helm chart. created an AWS cluster and peered with the GCP cluster and deployed the Jenkins modules using both local offload strategy, remote offload strategy. so, for local, it's working fine but while using the remote offload strategy we are facing the issue mentioned below:
The Jenkin pod is going into a crashloopbackoff state after a long time it is going into a terminate state.
FYI: 
![image](https://github.com/liqotech/liqo/assets/139134201/850fb2fa-7b2a-4aa3-8119-bfc2f982529a)

#### What you expected to happen:

After applying the remote offload strategy to deploy the Jenkins module, the Jenkin pods should be in a running state.

#### How to reproduce it (as minimally and precisely as possible):
1. Created the AWS cluster and GCP cluster.
2. Peered AWS cluster with GCP cluster.
3. Deployed the Jenkins module in the AWS cluster using a remote offload strategy.

#### Environment:
- Liqo version: 
  Client version: v0.6.0
  Server version: v0.6.0

- Kubernetes version (use `kubectl version`):
   Client Version: v1.25.5
   Kustomize Version: v4.5.7
   Server Version: v1.25.11-eks-a5565ad

- Cloud provider or hardware configuration:
   AWS and GCP
- Network plugin and version: 
  amazon-k8s-cni:v1.12.2-eksbuild.1
- Install tools: 
- Others:

**Comment by cheina97** [comment]
Hi @shegurisuresh, as already explained here https://liqo-io.slack.com/archives/C014Z7F25KP/p1686499731025629?thread_ts=1686498579.937339&cid=C014Z7F25KP the problem is not related to Liqo.

`when pods are reflected by Liqo, the service-account is mounted in this folder /var/run/secrets/kubernetes.io/serviceaccount. I think the problem is that your container is trying to get the service account from an external resource and not from the one mounted inside your pod.`

**Comment by shegurisuresh** [comment]
Hi @cheina97, I have manually added the GCP service token to the AWS config file but still, the Jenkins pods status is not in running state.
