### ISSUE TITLE
Issue on liqo uninstallation

### ISSUE THREAD

**Issue by thisiskazem** [liqotech/liqo#2821]
Hello everyone.

I have a central kubernetes cluster implemented on OpenStack with 3 machines (1 server and 2 agents) with k3s installed on it using:
`curl -sfL https://get.k3s.io | sh -s - server --disable traefik --node-external-ip <PUBLIC_IP_ADDRESS>`

and an edge node which is a minipc with k3s installed using:
`sudo curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" sh -s - --write-kubeconfig-mode 644-`

This is the installed version of liqo on both sides:
![Screenshot from 2024-11-21 11-58-50](https://github.com/user-attachments/assets/eff52a13-1ea3-429a-9948-a8c5ac94c2d3)

I was trying to establish liqo peering on the edge node (minipc) using this command:
`liqoctl peer --in-band --remote-kubeconfig <KUBECONFIG_FILE> --server-service-type NodePort`
 but it stuck at this stage:
Waiting for Connection status to be established

Then I tried to uninstall liqo using `liqoctl uninstall --purge` but it returned me this message:
 ERRO  Pre-uninstall checks failed: you should:                                                                                                           
       disable networking for clusters:
       - snowy-water

I need to remove all the clusterroles, clusterrolebindings, customresourcedefinition, services, deployments, daemonsets, pods, cronjob.batch, namespaces, mutatingwebhookconfigurations and validatingwebhookconfiguration related to liqo to be able to uninstall liqo itself.

**Comment by claudiolor** [comment]
Hi @thisiskazem, thanks for opening an issue.

I believe this is an expected behaviour. If you notice the error message is saying that the network needs to be disabled for peer `snowy-water`, so there is an active peering, even though it is broken and if you run `liqoctl info` you should be able to see that there is a peering with that cluster (maybe with unhealthy network).

At the moment, it is not possible to uninstall Liqo until there are active peerings, so this is expected.

In your case to be able to unistall Liqo you can launch `liqoctl unpeer` to remove any active peerings. Only at that point, you should be able to smoothly uninstall Liqo.

Maybe what we can do is making the error message more explicit, telling the user to use `liqoctl unpeer` to remove the active peerings.

**Comment by frisso** [comment]
@claudiolor i agree that the message should be more clear: "disable networking for clusters" could be replaced with "unpeer following clusters..."
