### ISSUE TITLE
Virtual Node Not Created

### ISSUE THREAD

**Issue by bogdan-ionescu** [liqotech/liqo#494]
**After installing Liqo, no virtual node is created on the Kubernetes cluster**
I'm looking for a solution to deploy geo-distributed read-only replicas for my application in the different data centers of my cloud provider (DigitalOcean) across the globe, closer to my client's servers, so I decided to give Liqo a try. However, the results I'm getting are quite different from what I see in the presentation video (https://www.youtube.com/watch?v=tHCKGwnmuAA), from the naming of the pods, to the virtual node not being created.

**Steps to Reproduce**
I've tried following the documentation (https://doc.liqo.io/user/gettingstarted/install/). However, small modifications were required, since at the first run, the default installation could not get the POD_CIDR and SERVICE_CIDR, so I've done this instead:

1. Get the Cluster Subnet and Service Subnet from the DigitalOcean Kubernetes cluster:
doctl kubernetes cluster get kubernetes-cluster-1-name

2. Export variables to make them available at Liqo installation time:
export POD_CIDR=10.244.0.0/16
export SERVICE_CIDR=10.245.0.0/16

3. Run the installation command again:
curl -sL https://get.liqo.io | bash

4. Wait until all pods are marked as "Running":
kubectl get po -n liqo

5. Check the cluster nodes to see if the virtual node is created, like in the video tutorial:
kubectl get no

**Expected behavior**
I would have expected to see a new node (the virtual node created by Liqo), but only my 2 initial Kubernetes nodes are present, without any new one.

**Screenshots**
<img width="457" alt="Screen Shot 2021-02-22 at 5 56 59 PM" src="https://user-images.githubusercontent.com/5028792/108735934-c3977200-7539-11eb-8ade-28d1ce60b333.png">

<img width="299" alt="Screen Shot 2021-02-22 at 6 13 42 PM" src="https://user-images.githubusercontent.com/5028792/108736040-e2960400-7539-11eb-87bc-de9090fd6de2.png">

Questions:
- What am I doing wrong? Is this virtual node still created with the latest version?
- How can I access the graphic dashboard? Maybe there are things I don't yet understand that will make more sense after checking the dashboard.
- Is Liqo the right solution for such a geo-distribution? Will I be able to specify which pods should be offloaded and where, in case of multiple clusters? (for example, I would need the application and a database replica to be always located in the same cluster, to prevent latency)

Thanks!

**Comment by frisso** [comment]
Bogdan,
1) unfortunately, the current peering process is really prone by errors. This is the reason we're creating an helm chart to simplify the installation, which should be ready (and documented) in a few days. As a short answer to your question, yes, you should see one more node in your cluster.
2) The graphic dashboard was available in version 0.1 but, due to the many changes we did in 0.2, it is of little use nowadays.
3) Yes, this is possible, but everything has to be done manually, unfortunately.

Final remark: Liqo is not yet for production; many problems can be solved, but require somebody in our team to help you on that matter. For this reason, I would suggest to join our Slack workspace and start "begging" our engineers in the help channel.

**Comment by bogdan-ionescu** [comment]
Thanks Fulvio!

I've joined the Slack workspace and I'll keep an eye for the release of the helm chart.
