### ISSUE TITLE
Pods hang in terminating status

### ISSUE THREAD

**Issue by giorio94** [liqotech/liqo#598]
**Describe the bug**

When a pod is deleted in the local cluster (manually, or through a scale operations), it triggers the transition into terminating status and the removal of the remote replicaset. Although the remote replicaset is correctly deleted, and the finalizer of the local pod is removed, it nonetheless continues hanging in the terminating status, until the termination grace period expires.

**To Reproduce**
1. Establish a liqo peering with a remote cluster
2. Create a pod, forcing the scheduling in the remote cluster (optionally, increase the termination grace period to better observe the behavior) 
3. Delete the pod
4. Observe it remains in terminating status until the termination grace period expires.

**Expected behavior**
The pod should be correctly deleted when the remote replicaset removal succeeded

**Comment by filippoprojetto** [comment]
I am investigating this issue. 

I have a question about the desired behaviour when handling pods deletion. From the implementation it looks like that receiving a `nil` pod object should make the kubelet raise an error but the tests assert the opposite. The test does not fail because the `CreatePod` function is called instead of `DeletePod` - fixing that the test fails as expected. 
Impl: https://github.com/liqotech/liqo/blob/5b7d99ad29ef7de2eda628e99c5b8b487e291780/pkg/virtualKubelet/provider/pods.go#L102 
Test: https://github.com/liqotech/liqo/blob/5b7d99ad29ef7de2eda628e99c5b8b487e291780/pkg/virtualKubelet/provider/pods_test.go#L135 

I see that both the Create and Update functions do not return an error when a nil pod is received. Is there a reason for the DeletePod function to deviate from this behaviour?

**Comment by filippoprojetto** [comment]
It looks like these 3 functions where all returning an error when getting a `nil` pod but it was changed with [this](https://github.com/liqotech/liqo/pull/500) PR. Was it intentional to let the `DeletePod` function behind?

**Comment by giorio94** [comment]
Trying to answer, although I wasn't involved in the virtual kubelet at that time and so I may be wrong.

AFAIK, the changes brought in by that PR were a sort of workaround to prevent a pod from being marked as failed in certain (race) conditions. Though, I feel they should be sooner or later reevaluated (e.g. after the upstream virtual kubelet code will be removed from the repository), since nil pods should never reach those functions in the first place. I believe the delete one was left out by mistake (as you pointed out the test is also broken), but cannot say for sure. Unrelated from this, but in the same file also the `GetPod` function is broken, as it always return nil due to the check on the return value. IMHO, this should also be fixed in a future major refactoring of the provider code.

**Comment by filippoprojetto** [comment]
I see. What if we removed the misleading test case? It does not add value as it is and we don't know/want to prioritise handling the nil pod scenario.

**Comment by giorio94** [comment]
I agree. It may be changed to DeletePod, asserting an error is correctly returned.
