### ISSUE TITLE
[Feature] Simplify the resource naming of Liqo resources

### ISSUE THREAD

**Issue by palexster** [liqotech/liqo#966]
So far, Liqo resources were named after the remote cluster id. To simplify the interaction with those resources, we would like to have pretty names for resources, which are easier to understand for users. This problem is particularly true when Liqo manages a lot of clusters, and it is hard to understand which cluster is involved.

Strategy: Liqo should use a unique local name to access resources locally; Liqo will use a hash of the UUID (max six characters) for remote disambiguation.

Tasks:

Rename LOCAL resources according to the new strategy starting from:

- [x] ForeignClusters
- [x] Nodes
- [x] NetworkConfig (from GenerateName)
- [x] TunnelEndpoint (from GenerateName)
- [x] Tenant
- [x] Tenant Namespaces
- [x] ResourceOffers (named after the cluster that created it)
- [x] ResourceRequests (named after the cluster that created it)

Rename REMOTE resources according to the new strategy starting from:
- [x] Application Namespaces

**Comment by CapacitorSet** [comment]
I can't remember if this was discussed in the relevant call, but what happens if two discovered clusters share the same cluster name (and would therefore create eg. the same tenant namespaces)? I think this situation should be avoided by assigning discovered clusters a new name if a conflict occurs, but let's discuss this in tomorrow's standup.
